secret: LTC_CMS_SECRET
admin:
  name: admin
  password: 123456sd
  email: habib@cyber-crafts.com
user:
  defaultPermissions:
    -   name: perm1
        data: {}
emails:
  adminCreated:
    subject: Hasan Kutbi - admin account data
    templatePath: __tests__/modules/User/adminCreatedTemp.ejs
  addUser:
    subject: Hasan Kutbi - Welcome to Arabian drive
    templatePath: __tests__/modules/User/registerTemp.ejs
  register:
    subject: Hasan Kutbi - Welcome to Arabian drive
    templatePath: __tests__/modules/User/registerTemp.ejs
  resetPassword:
    subject: Hasan Kutbi - Password reset request
    templatePath: __tests__/modules/PasswordReset/resetPasswordTemp.ejs

roles:
  - name: some-role
    permissions:
      -   name: perm2
          data: {}
    description: something

maxAllowedFailedAttempts: 5
lockOutPeriod: 60                         # in seconds
passwordExpirationPeriod: 100             # in days