secret: LTC_CMS_SECRET
admin:
  name: admin
  password: 123456sd
  email: habib@cyber-crafts.com
user:
  defaultPermissions: [login]

registerMessage: <h3>Welcome <<name>>, </h3><br> <p>Your registration is successful</p>
resetPasswordMessage: "<h3>Dear <<name>>, </h3><br> <p>Your password reset key is: </p><br><span><<passwordResetCode>></span>"
adminCreationSubject: Hasan Kutbi - admin account data
addUserSubject: Hasan Kutbi - Welcome to Arabian drive
registerSubject: Hasan Kutbi - Welcome to Arabian drive
resetPasswordSubject: Hasan Kutbi - Password reset request
emails:
  adminCreated:
    subject: Hasan Kutbi - admin account data
    templatePath: __tests__/modules/User/adminCreatedTemp.ejs
  addUser:
    subject: Hasan Kutbi - Welcome to Arabian drive
    templatePath: __tests__/modules/User/registerTemp.ejs
  register:
    subject: Hasan Kutbi - Welcome to Arabian drive
    templatePath: __tests__/modules/User/registerTemp.ejs
  resetPassword:
    subject: Hasan Kutbi - Password reset request
    templatePath: __tests__/modules/PasswordReset/resetPasswordTemp.ejs